### ISSUE TITLE
Test Check multiplying by infinity returns infinity 

### ISSUE THREAD

**Issue by LLFourn** [LLFourn/secp256kfun#13]
see: https://github.com/bitcoin-core/secp256k1/pull/791/files

**Comment by elichai** [comment]
Note, that generally the high level API of libsecp256k1 *Doesn't* support points at infinity, because those aren't valid public keys and don't have any meaningful serialization

**Comment by LLFourn** [comment]
This is about the Low level API (`ecmult` and `ecmult_const`). It turns out that I was allowing infinity to be passed down to these and then panicking. 

The solution is just to check for that and early exit. This is what gmax was suggesting here https://github.com/bitcoin-core/secp256k1/pull/791 (I followed up suggesting it should be applied to `ecmult` as well).
