### ISSUE TITLE
Participate in FROST Implementers Workshop September 18th?

### ISSUE THREAD

**Issue by ChristopherA** [LLFourn/secp256kfun#193]
We are hosting our send FROST library implementors workshop on September 18th https://developer.blockchaincommons.com/frost/meeting2/

So far scheduled are some discussion from bitcoin devs on their FROST implementations in C++. One of the critical issues to me are the issues of x-only pubkey compatibility and the tweaked signatures for use on-chain. All of Blockchain Common's own code base has been moving from C++ to Rust and we'd prefer a rust implementation.

Could we get someone from this team to participate, or even present a brief status update / roadmap on this project? Contact me at ChristopherA@LifeWithAlacrity.com if you are interested.

Thanks!

**Comment by LLFourn** [comment]
Hi @ChristopherA sorry for late response. Looks like I missed this one. Thanks for hosting this I'll check out the video.
