### ISSUE TITLE
evaluate k256 as backend 

### ISSUE THREAD

**Issue by LLFourn** [LLFourn/secp256kfun#7]
~~@tarcieri~~ @tuxxy  has (seemingly recently) [implemented] and even exposed the arithmetic for secp256k1.
It would be good to evaluate it as a backend. Upon quick review: 
- The arithmetic is nicely documented well referenced and cleanly implemented 
- Uses 64-bit limbs for arithmetic (unlike current 32-bit).
- Uses Projective coords rather than Jacobian (we'd need to stop calling non-affine things `Jacobian` but that's fine)
- No implementation of Shamir's trick etc or other multi scalar multiplication
- No ability to precompute arithmetic tables for generators.

But it looks like it has everything to at least implement the API required. Performance will matter but I think that having simpler arithmetic counts for a lot in my mind.

[implemented]: https://github.com/RustCrypto/elliptic-curves/blob/master/k256/README.md

**Comment by tarcieri** [comment]
FYI, the crate was written by @tuxxy

**Comment by LLFourn** [comment]
A stripped down backend with just the k256 arithmetic was merged in #74
