### ISSUE TITLE
`proptest` feature

### ISSUE THREAD

**Issue by thomaseizinger** [LLFourn/secp256kfun#72]
It would be helpful for downstream crates to add a `proptest` feature and implement the `Arbitrary` trait for various low-level types like `Point`.

Proptest has released a 1.0.0 which makes it a decent candidate to depend on for wider ecosystem compatibility: https://docs.rs/proptest/1.0.0/proptest/

**Comment by LLFourn** [comment]
Yes let's do it. Also should dogfood it by using in the tests here.
